[[install-from-rpm]]
<<<
== Installation from RPM

=== Overview

There is a public http://ngageoint.github.io/geowave/packages.html[GeoWave RPM Repo] available with the following packages.
As you'll need to coordinate a restart of Accumulo to pick up changes to the GeoWave iterator classes the repos default to
be disabled so you can keep auto updates enabled. When ready to do an update simply add `--enablerepo=geowave` to your
command. The packages are built for a number of different hadoop distributions (Cloudera, Hortonworks and Apache) the RPMs
have the vendor name embedded as the second portion of the rpm name (geowave-apache-accumulo, geowave-hdp2-accumulo or geowave-cdh5-accumulo)

=== Examples

[source, bash]
----
# Use GeoWave repo RPM to configure a host and search for GeoWave RPMs to install
rpm -Uvh http://s3.amazonaws.com/geowave-rpms/release/noarch/geowave-repo-1.0-3.noarch.rpm
yum --enablerepo=geowave search geowave

# Install GeoWave Accumulo iterator on a host (probably a namenode)
yum --enablerepo=geowave install geowave-cdh5-accumulo

# Update
yum --enablerepo=geowave install geowave-*
Restart Accumulo service
----

==== RPM Descriptions

Some packages are compiled for a specific vendor release and are shown in the table below with a $VENDOR label in the name. Other packages like
documentation are the same for any installation. The table below lists all of the available packages, gives a brief description of what they contain
and where they might be installed in various deployment scenarios.

.GeoWave RPMs
[cols="3*", options="header"]
|===
|Name
|Description
|Usage

|geowave-$VENDOR-accumulo
|GeoWave custom Accumulo iterator and helper classes
|This RPM installs the geowave-accumulo.jar locally and then with a hadoop fs -put command copies the file into HDFS. Needs to be installed on a node with the hadoop binary and connectivity to HDFS like the namenode.

|geowave-core
|Core ensures the GeoWave home directory and user have been created
|All other RPMs depend on this one so it will be installed for you when installing other packages

|geowave-docs
|Documentation (HTML, PDF, EPUB and man pages)
|Optional package that installs the documentation on any node

|geowave-$VENDOR-ingest
|Ingest Tool
|Optional package that installs the command line ingest tool on any node from which you'd like to use to ingest data

|geowave-$VENDOR-jetty
|GeoServer components installed into /usr/local/geowave/geoserver and available at http://FQDN:8080/geoserver
|Optional package that uses the GeoServer plugin to provide access to ingested data via OGC services

|geowave-puppet
|Puppet Scripts
|Optional package that will install the GeoWave Puppet module onto a Puppet server

|geowave-$VENDOR-single-host
|All GeoWave Components installed on a single host (sometimes useful for development)
|Optional meta-package that has dependencies on all other packages. Will install everything on one node for the development deployment scenario

|geowave-repo
|GeoWave RPM Repo config file
|Optional package that will install the GeoWave Release RPM Repo configuration onto any host

|geowave-repo-dev
|GeoWave Development RPM Repo config file
|Optional package that will install the GeoWave Development RPM Repo configuration onto any host

|===


=== RPM Installation Notes

geowave-cdh5-accumulo: This RPM will install the GeoWave Accumulo iterator into the local file system and then upload
it into HDFS using the `hadoop fs -put` command. This means of deployment requires that the RPM is installed on a node that
has the correct binaries and configuration in place to push files to HDFS, like your namenode.

With the exception of the Accumulo RPM mentioned above you can install the rest of the RPMs all on a single node or
a mix of nodes depending on your cluster configuration. All GeoWave files get installed into the `/usr/local/geowave/' directory
